describe("When testing the sums calculator module", function()
    it("Should return 385 as the sum of squares from 1 to 10", function()
        local sums_calculator = require("../sums_calculator")
        local result = sums_calculator.sum_of_squares_of(10)
        assert.are.same(385, result)
    end)

    it("Should return 3025 as the square of sums from 1 to 10", function()
        local sums_calculator = require("../sums_calculator")
        local result = sums_calculator.square_of_sums_of(10)
        assert.are.same(3025, result)
    end)

    it("Should return 2640 as the difference between the sum of the squares and the square of the sum of 1 to 10", function()
        local sums_calculator = require("../sums_calculator")
        local result = sums_calculator.diff_between_square_of_sums_and_sum_of_squares_of(10)
        assert.are.same(2640, result)
    end)

    it("Should return X as the difference between the sum of the squares and the square of the sum of 1 to 100", function()
        local sums_calculator = require("../sums_calculator")
        local result = sums_calculator.diff_between_square_of_sums_and_sum_of_squares_of(100)
        assert.are.same(25164150, result)
    end)
end)